import type { Metadata } from "next";
import { personalInfo } from "@/data";

export const siteConfig: Metadata = {
  title: `${personalInfo.name} | AI Web Developer`,
  description: personalInfo.bio,
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
    "web development",
    "ai automation",
    "freelancer",
    "uk developer",
  ] as Array<string>,
  authors: {
    name: personalInfo.name,
    url: "https://skyweb.co.uk",
  },
} as const;
